name    = "WiSARD"
uuid    = "2b71b7a6-5a26-4a05-9b8d-679d5aa759d4"
authors = ["pedromxavier <pedromxavier@poli.ufrj.br>"]
version = "0.3.4"

[deps]
Random           = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
julia = "1.6"
